### PR TITLE
Fixes example_keras_to_qkeras.py script

### LINKED ISSUE #22: Getting 'TypeError: cannot unpack non-iterable Model object' error when trying to run example_keras_to_qkeras.py
I am getting error "TypeError: cannot unpack non-iterable Model object" when trying to run the example_keras_to_qkeras.py script.

I installed all requirements using

`pip install -r requirements.txt`

And then run

`pip install .`

And

`python setup.py install`

### PR DESCRIPTION
**Pull request by fPecc**
Fixes #22

### CODE REVIEW

**Comment by fPecc** [comment]
@googlebot I fixed it.

**Comment by zhuangh** [comment]
@fPecc thanks for the PR! but I saw cla is still required to sign from our end.

**Comment by fPecc** [comment]
@googlebot I fixed it.

**Comment by zhuangh** [comment]
sorry @fPecc in our backend system, it still shows need_author_cla, please check whether you use the right email or right license https://opensource.google/docs/cla/#external-contributors. 

And vloncar mentioned it was fixed via https://github.com/google/qkeras/issues/22#issuecomment-622327677

**Pull request closed without merging**
